# Use the color palette
palette = "dracula"

format = """
[░▒▓](current_line)\
$os\
$username\
$sudo\
$hostname\
[░▒▓](bg:current_line fg:purple)\
$directory\
[▒█](bg:purple fg:cyan)\
$c\
$conda\
$dart\
$elixir\
$elm\
$golang\
$haskell\
$haxe\
$java\
$julia\
$lua\
$meson\
$nim\
$nix_shell\
$nodejs\
$python\
$rlang\
$ruby\
$rust\
$php\
$scala\
$package\
[▒█](bg:cyan fg:comment)\
$cmd_duration\
[▛](bg:#000 fg:comment)\
(
[░▒▓](current_line)\
[ $git_metrics](bg:current_line fg:foreground)\
[░▒▓](bg:current_line fg:orange)\
$git_branch\
[▒█](bg:orange fg:pink)\
$git_status\
[▛](bg:#000 fg:pink))
[░▒▓](current_line)\
[$status ($shell)](bg:current_line)\
[▛](current_line) \
"""
[username]
show_always = true
style_user = "bg:current_line fg:foreground"
style_root = "bg:red fg:foreground"
format = '[$user ]($style)'
disabled = false

[hostname]
ssh_symbol = " "
ssh_only = true
style = "bg:current_line fg:foreground"
format = '[$ssh_symbol$hostname ]($style)'
disabled = false

[os]
style = "bg:current_line fg:foreground"
disabled = false
[os.symbols]
Alpaquita = " "
Alpine = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Windows = "󰍲 "

[sudo]
style = 'bg:current_line fg:pink bold'
symbol = ''
disabled = false
allow_windows = true

[directory]
style = "bg:purple fg:background"
format = "[$path ]($style)"
truncation_length = 3
truncation_symbol = "…/"
read_only = " 󰌾"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:orange fg:background"
format = '[$symbol $branch ]($style)'

[git_status]
style = "bg:pink fg:background"
conflicted = '󰞇 '
up_to_date = ' '
untracked = ' '
stashed = ' '
modified = '󱓥 '
staged = '[󱫉\($count\)](backgroundn) '
renamed = ' '
deleted = ' '
ahead = '${count} '
diverged = '${ahead_count}${behind_count} '
behind = '${count} '
format = '[$all_status$ahead_behind]($style)'

[git_metrics]
disabled = false
deleted_style = "bg:current_line fg:red"
added_style = "bg:current_line fg:green"
format = '([$added]($added_style))([$deleted]($deleted_style) )'

[c]
symbol = " "
style = "bg:cyan fg:background"
format = '([$symbol($version) ]($style))'

[conda]
symbol = " "
style = "bg:cyan fg:background"
format = '([$symbol($version) ]($style))'

[dart]
symbol = " "
style = "bg:cyan fg:background"
format = '([$symbol($version) ]($style))'

[elixir]
symbol = " "
style = "bg:cyan fg:background"
format = '([$symbol($version) ]($style))'

[elm]
symbol = " "
style = "bg:cyan fg:background"
format = '([$symbol($version) ]($style))'

[golang]
symbol = " "
style = "bg:cyan fg:background"
format = '([$symbol($version) ]($style))'

[haskell]
symbol = " "
style = "bg:cyan fg:background"
format = '([$symbol($version) ]($style))'

[haxe]
symbol = " "
style = "bg:cyan fg:background"
format = '([$symbol($version) ]($style))'

[java]
symbol = " "
style = "bg:cyan fg:background"
format = '([$symbol($version) ]($style))'

[julia]
symbol = " "
style = "bg:cyan fg:background"
format = '([$symbol($version) ]($style))'

[lua]
symbol = " "
style = "bg:cyan fg:background"
format = '([$symbol($version) ]($style))'

[meson]
symbol = "󰔷 "
style = "bg:cyan fg:background"
format = '([$symbol($version) ]($style))'

[nim]
symbol = "󰆥 "
style = "bg:cyan fg:background"
format = '([$symbol($version) ]($style))'

[nix_shell]
symbol = " "
style = "bg:cyan fg:background"
format = '([$symbol($version) ]($style))'

[nodejs]
symbol = " "
style = "bg:cyan fg:background"
format = '([$symbol($version) ]($style))'

[python]
symbol = " "
style = "bg:cyan fg:background"
format = '([$symbol($version) ]($style))'

[rlang]
symbol = "󰟔 "
style = "bg:cyan fg:background"
format = '([$symbol($version) ]($style))'

[ruby]
symbol = " "
style = "bg:cyan fg:background"
format = '([$symbol($version) ]($style))'

[rust]
symbol = " "
style = "bg:cyan fg:background"
format = '([$symbol($version) ]($style))'

[php]
symbol = " "
style = "bg:cyan fg:background"
format = '([$symbol($version) ]($style))'

[scala]
symbol = " "
style = "bg:cyan fg:background"
format = '([$symbol($version) ]($style))'

[package]
symbol = "󰏗 "
style = "bg:cyan fg:background"
format = '([$symbol($version) ]($style))'

[cmd_duration]
min_time = 1_000
min_time_to_notify = 30_000
show_milliseconds = true
disabled = false
style = "bg:comment fg:background"
show_notifications = true
format = '[󰅒 $duration]($style)'

[status]
disabled = false
style = "bg:current_line fg:background"
symbol = '[󰚌](bg:current_line fg:red)'
success_symbol = '[󰮭](bg:current_line fg:green)'
format = '[$symbol ]($style)'

[shell]
style = "bg:current_line"
cmd_indicator = "[](bg:current_line fg:yellow)"
bash_indicator = "[](bg:current_line fg:green)"
fish_indicator = "[󰈺](bg:current_line fg:CYAN)"
nu_indicator = "[󰫻󰬂](bg:current_line fg:green)"
powershell_indicator = "[󰨊](bg:current_line fg:blue)"
unknown_indicator = "[](bg:current_line fg:red)"
disabled = false

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

# Define Dracula color palette
[palettes.dracula]
background = "#282a36"
current_line = "#44475a"
foreground = "#f8f8f2"
comment = "#6272a4"
cyan = "#8be9fd"
green = "#50fa7b"
orange = "#ffb86c"
pink = "#ff79c6"
purple = "#bd93f9"
red = "#ff5555"
yellow = "#f1fa8c"
